### ISSUE TITLE
Can I use the click event

### ISSUE THREAD

**Issue by de-raaf-media** [cotton123236/zoomist#15]
Hi, great work on this library. I want to use this and after zooming and dragging use the click event to get coordinates of the position I clicked on the image. But it seems I am not able to use the click event. Can I override this somehow?

Regards
Mark

**Comment by de-raaf-media** [comment]
Figured it out. This seems to work:

zoomist.addEventListener('click', function (event) {});

**Comment by cotton123236** [comment]
Hi Mark,
you can get the position by using event **dragEnd**
`zoomist.on('dragEnd', (transform, event) => { console.log(event) })`
