### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Alex-Indilex** [cotton123236/zoomist#30]
Uncaught SyntaxError: Unexpected token 'export' (at zoomist.min.js:7:17636)

**Comment by cotton123236** [comment]
Hey @Alex-Indilex 
Could you please describe your problem in more detail?
There is no `zoomist.min.js` file in version 2.X.

**Comment by Alex-Indilex** [comment]
I took the link from this site https://cotton123236.github.io/zoomist/index.html

**Comment by daveherman71** [comment]
@Alex-Indilex - see my workaround in the issue that I logged https://github.com/cotton123236/zoomist/issues/31

**Comment by cotton123236** [comment]
@Alex-Indilex @daveherman71 

Sorry, I forgot to update the documentation. I fixed it already.
If you want to use CDN for v1:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/zoomist@1/dist/zoomist.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/zoomist@1/dist/zoomist.min.js"></script>
```

But I highly recommend you can use v2, you can find the usage in [github README.md](https://github.com/cotton123236/zoomist) .
