### ISSUE TITLE
Zoomist v2.0 does not work

### ISSUE THREAD

**Issue by daveherman71** [cotton123236/zoomist#31]
Zoomist v2.0 no longer works.

Using the CDN version - https://cdn.jsdelivr.net/gh/cotton123236/zoomist@latest/dist/zoomist.min.js

The following error is displayed in Chrome:
```
zoomist.min.js:7
Uncaught SyntaxError: Unexpected token 'export' (at zoomist.min.js:7:17636)
```
And in Firefox:
```
zoomist.min.js:7
Uncaught SyntaxError: export declarations may only appear at top level of a module
```
This appears in all version 2 packages.

The last working commit was on 11 August 2022.
https://github.com/cotton123236/zoomist/tree/bdf1158e9022c6eb161ad92095c703df855c0508

This version includes the dist/zoomist.min.js file which works correctly.

**Comment by cotton123236** [comment]
Hey @daveherman71 ,
That is because the latest version of Zoomist is 2.X now!
If you want to use Zoomist v1 you can checkout [branch v1](https://github.com/cotton123236/zoomist/tree/v1)
CDN of v1:
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/zoomist@1/dist/zoomist.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/zoomist@1/dist/zoomist.min.js"></script>
```
If you want to use v2 please checkout branch main and you can find the usage in README.md .

**Comment by daveherman71** [comment]
Thanks Wilson.

Please note that JSDelivr is serving the incorrect URLs for v1.x.

Navigate to https://www.jsdelivr.com/package/npm/zoomist and select any v1.x package and you will get:
```
<script src="https://cdn.jsdelivr.net/npm/zoomist@1.0.2/zoomist.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/zoomist@1.0.2/zoomist.min.css" rel="stylesheet">
```
These URLs are incorrect.

They should be:
```
<script src="https://cdn.jsdelivr.net/npm/zoomist@1.0.2/dist/zoomist.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/zoomist@1.0.2/dist/zoomist.min.css" rel="stylesheet">
```
Please note the additional **/dist/** subfolder.
