### ISSUE TITLE
Zoomer buttons cause a form submition

### ISSUE THREAD

**Issue by pepkin88** [cotton123236/zoomist#39]
Because the zoomer buttons don't have the type attribute set on them, it gets the default value, which is submit. That's why when Zoomist gets instantiated inside a form, clicking on those button will cause a form submission.

The solution to this would be [setting the type attribute to `"button"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type) upon the element creation.

**Comment by adriallongarriu** [comment]
I was having the same problem issue. 
For now I used the following code to fix it temporarily:
```javascript
const zoomist = new Zoomist('.zoomist-container', {
      on: {
          ready(zoomist, scale) {
            $('.zoomist-zoomer-button').attr("type", "button");
          }
        }
  })
```
After ready and the buttons are created add the type `"button"`

**Comment by cotton123236** [comment]
Hey @pepkin88 @adriallongarriu ,

The buttons are set the type attribute to button by default now. Thanks for waiting and liking this library!
