### ISSUE TITLE
TS definitions

### ISSUE THREAD

**Issue by scriptSQD** [cotton123236/zoomist#5]
Hi there! I didn't know any other place to reach you, so here I am.  
I've made Ts definitions for your library on DefinitelyTyped, maybe you wouldn't mind to review them and help me maintain them?  
I'm using them in a tricky way through my git repo, so I want them to be published ASAP.  
Thanks in advance for your assistance!

**Comment by cotton123236** [comment]
Hey @scriptSQD 
Sorry I'm not a TS developer, so I don't know much about DefinitelyTyped.
But I would love to help you maintain them.
If you can tell me what to do or what can I do, I'll be very thankful!
You can reach me through email cotton123236@gmail.com

**Comment by scriptSQD** [comment]
Ok, pretty late, but everything's finally fine! Closing this one
